// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleGatewayWithDb.Data;

#nullable disable

namespace SampleGatewayWithDb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517115200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleGatewayWithDb.Data.CertificateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("ntext");

                    b.Property<int?>("EndpointId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique()
                        .HasFilter("[EndpointId] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.EndpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TimeoutSeconds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.TenantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultEndpointName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HandlerLifetimeSeconds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TimeoutSeconds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.TenantHeaderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantHeaders");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.CertificateEntity", b =>
                {
                    b.HasOne("SampleGatewayWithDb.Data.EndpointEntity", "Endpoint")
                        .WithOne("Certificate")
                        .HasForeignKey("SampleGatewayWithDb.Data.CertificateEntity", "EndpointId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SampleGatewayWithDb.Data.TenantEntity", "Tenant")
                        .WithOne("Certificate")
                        .HasForeignKey("SampleGatewayWithDb.Data.CertificateEntity", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Endpoint");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.EndpointEntity", b =>
                {
                    b.HasOne("SampleGatewayWithDb.Data.TenantEntity", "Tenant")
                        .WithMany("Endpoints")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.TenantHeaderEntity", b =>
                {
                    b.HasOne("SampleGatewayWithDb.Data.TenantEntity", "Tenant")
                        .WithMany("DefaultHeaders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.EndpointEntity", b =>
                {
                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("SampleGatewayWithDb.Data.TenantEntity", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("DefaultHeaders");

                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
